# Generated by Django 5.2.4 on 2025-08-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('web', models.URLField()),
                ('cv', models.FileField(upload_to='apply/')),
                ('counvert', models.CharField(max_length=500)),
            ],
        ),
    ]
